# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QVBoxLayout, QHBoxLayout, QLabel, QPushButton, QComboBox
from PyQt5.QtGui import QFont


class Ui_MainWindow(object):
    def setup_ui(self, MainWindow):
        MainWindow.setObjectName("rPPG-HRV情绪识别系统")
        MainWindow.resize(1080, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.main_layout = QVBoxLayout()
        self.top_layout = QHBoxLayout()
        self.operations_info_layout = QVBoxLayout()

        # 多选框，用于选择信号计算方式
        self.comboBox = QComboBox()
        self.comboBox.setMinimumSize(QtCore.QSize(0, 28))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 28))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("GREEN")
        self.comboBox.addItem("GREEN-RED")
        self.comboBox.addItem("CHROM")
        self.comboBox.addItem("PBV")
        self.comboBox.addItem("POS")
        self.comboBox.setMinimumWidth(350)

        # 显示原始信号、滤波信号的按钮
        self.Button_Raw = QPushButton()
        self.Button_Raw.setText("原始信号")
        self.Button_Filtered = QPushButton()
        self.Button_Filtered.setText("滤波信号")

        # 显示FPS、BPM等信息的标签
        self.info_label = QLabel()
        self.info_label.setMinimumSize(QtCore.QSize(0, 300))
        self.info_label.setFont(QFont("Consolas", 18))
        self.info_label.setText("")
        self.info_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.info_label.setObjectName("info")

        self.operations_info_layout.addWidget(self.comboBox)
        self.operations_info_layout.addWidget(self.Button_Raw)
        self.operations_info_layout.addWidget(self.Button_Filtered)
        self.operations_info_layout.addWidget(self.info_label)

        # 摄像头画面
        self.face = QtWidgets.QLabel(self.centralwidget)
        self.face.setFixedSize(480, 280)
        self.face.setScaledContents(True)

        self.top_layout.addLayout(self.operations_info_layout)
        self.top_layout.addStretch()
        self.top_layout.addWidget(self.face)

        self.bottom_layout = QHBoxLayout()

        self.Layout_BVP = QVBoxLayout()
        self.Layout_BVP.setContentsMargins(0, 0, 0, 0)

        self.Layout_Signal = QVBoxLayout()
        self.Layout_Signal.setContentsMargins(0, 0, 0, 0)

        self.Layout_Spec = QVBoxLayout()
        self.Layout_Spec.setContentsMargins(0, 0, 0, 0)

        self.bottom_layout.addLayout(self.Layout_BVP)
        self.bottom_layout.addLayout(self.Layout_Spec)
        self.bottom_layout.addLayout(self.Layout_Signal)

        self.main_layout.addLayout(self.top_layout)
        self.main_layout.addLayout(self.bottom_layout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.centralwidget.setLayout(self.main_layout)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

